/**
 * Screen usage: identical to web. Import the generated TanStack option/key
 * factories — types for params, body, and response are all inferred from the
 * Rust DTOs via the OpenAPI spec.
 *
 * Generated by the `@tanstack/react-query` hey-api plugin:
 *   - <op>Options(input)   → pass to useQuery / useSuspenseQuery / prefetchQuery
 *   - <op>QueryKey(input)  → stable key for invalidation
 *   - <op>Mutation()       → pass to useMutation
 */
import React from 'react';
import { ActivityIndicator, Button, FlatList, Text, View } from 'react-native';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';

import {
  getPostOptions,
  listPostsOptions,
  listPostsQueryKey,
  createPostMutation,
} from '../../ts/hey-api/@tanstack/react-query.gen';

export function PostDetailScreen({ id }: { id: string }) {
  // path param is type-checked: { path: { id: string } }
  const { data, isLoading, error } = useQuery(getPostOptions({ path: { id } }));
  //      ^ data: PostResponse | undefined

  if (isLoading) return <ActivityIndicator />;
  if (error) return <Text>Failed to load</Text>;

  return (
    <View>
      <Text>{data?.title}</Text>
      <Text>{data?.body}</Text>
      {/* discriminated union from the Rust enum is narrowed here */}
      {data?.status.type === 'published' && (
        <Text>published_at: {String(data.status.published_at)}</Text>
      )}
    </View>
  );
}

export function PostListScreen() {
  const qc = useQueryClient();
  const { data } = useQuery(listPostsOptions());
  //      ^ data: ListResponse_PostResponse | undefined

  const create = useMutation({
    ...createPostMutation(),
    onSuccess: () => {
      // typed invalidation — same key factory the query used
      qc.invalidateQueries({ queryKey: listPostsQueryKey() });
    },
  });

  return (
    <View>
      <FlatList
        data={data?.items ?? []}
        keyExtractor={(p) => p.id}
        renderItem={({ item }) => <Text>{item.title}</Text>}
      />
      <Button
        title={create.isPending ? 'Creating…' : 'New post'}
        disabled={create.isPending}
        onPress={() =>
          // body is type-checked against CreatePostRequest
          create.mutate({
            body: { title: 'Hello', body: 'from RN', tags: ['demo'] },
          })
        }
      />
    </View>
  );
}
