// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import { createPost, getPost, listPosts, type Options } from "../sdk.gen";
import type {
  CreatePostData,
  CreatePostError,
  CreatePostResponse,
  GetPostData,
  GetPostError,
  GetPostResponse,
  ListPostsData,
  ListPostsResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const listPostsQueryKey = (options?: Options<ListPostsData>) =>
  createQueryKey("listPosts", options);

export const listPostsOptions = (options?: Options<ListPostsData>) =>
  queryOptions<
    ListPostsResponse,
    DefaultError,
    ListPostsResponse,
    ReturnType<typeof listPostsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listPosts({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listPostsQueryKey(options),
  });

export const createPostMutation = (
  options?: Partial<Options<CreatePostData>>,
): UseMutationOptions<
  CreatePostResponse,
  CreatePostError,
  Options<CreatePostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreatePostResponse,
    CreatePostError,
    Options<CreatePostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getPostQueryKey = (options: Options<GetPostData>) =>
  createQueryKey("getPost", options);

export const getPostOptions = (options: Options<GetPostData>) =>
  queryOptions<
    GetPostResponse,
    GetPostError,
    GetPostResponse,
    ReturnType<typeof getPostQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getPostQueryKey(options),
  });
