// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  CreatePostData,
  CreatePostErrors,
  CreatePostResponses,
  GetPostData,
  GetPostErrors,
  GetPostResponses,
  ListPostsData,
  ListPostsResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const listPosts = <ThrowOnError extends boolean = false>(
  options?: Options<ListPostsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ListPostsResponses, unknown, ThrowOnError>({
    url: "/posts",
    ...options,
  });

export const createPost = <ThrowOnError extends boolean = false>(
  options: Options<CreatePostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreatePostResponses,
    CreatePostErrors,
    ThrowOnError
  >({
    url: "/posts",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const getPost = <ThrowOnError extends boolean = false>(
  options: Options<GetPostData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetPostResponses, GetPostErrors, ThrowOnError>(
    { url: "/posts/{id}", ...options },
  );
