// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * Reused author summary embedded in posts and comments.
 */
export type Author = {
  display_name: string;
  id: string;
};

export type Comment = {
  author: Author;
  created_at: number;
  id: string;
  text: string;
};

export type CreateCommentRequest = {
  text: string;
};

export type CreatePostRequest = {
  body: string;
  /**
   * Arbitrary metadata → `Record<string, string>` / `{ [key: string]: string }`.
   */
  metadata?: {
    [key: string]: string;
  };
  /**
   * Optional list → `string[] | undefined`.
   */
  tags?: Array<string> | null;
  title: string;
};

export type CreateUserRequest = {
  display_name: string;
  email: string;
  role?: null | UserRole;
};

export type ErrorResponse = {
  code: string;
  message: string;
};

/**
 * Generic paginated wrapper. utoipa monomorphizes per instantiation
 * (`ListResponse_PostResponse`, `ListResponse_UserResponse`, …).
 */
export type ListResponseComment = {
  bookmark?: string | null;
  items: Array<{
    author: Author;
    created_at: number;
    id: string;
    text: string;
  }>;
};

/**
 * Generic paginated wrapper. utoipa monomorphizes per instantiation
 * (`ListResponse_PostResponse`, `ListResponse_UserResponse`, …).
 */
export type ListResponsePostResponse = {
  bookmark?: string | null;
  items: Array<{
    /**
     * Nested object.
     */
    author: Author;
    body: string;
    /**
     * Nested array of objects.
     */
    comments: Array<Comment>;
    created_at: number;
    id: string;
    status: PostStatus;
    tags: Array<string>;
    title: string;
  }>;
};

/**
 * Generic paginated wrapper. utoipa monomorphizes per instantiation
 * (`ListResponse_PostResponse`, `ListResponse_UserResponse`, …).
 */
export type ListResponseUserResponse = {
  bookmark?: string | null;
  items: Array<{
    display_name: string;
    email: string;
    id: string;
    role: UserRole;
  }>;
};

export type PostResponse = {
  /**
   * Nested object.
   */
  author: Author;
  body: string;
  /**
   * Nested array of objects.
   */
  comments: Array<Comment>;
  created_at: number;
  id: string;
  status: PostStatus;
  tags: Array<string>;
  title: string;
};

/**
 * Plain enum used both as a field and as a query parameter → string union.
 */
export type PostSort = "newest" | "oldest" | "popular";

/**
 * Tagged enum → discriminated union. Three variants incl. data-carrying ones.
 */
export type PostStatus =
  | {
      type: "draft";
    }
  | {
      published_at: number;
      type: "published";
    }
  | {
      reason: string;
      type: "archived";
    };

/**
 * PATCH semantics: every field optional → partial update payload.
 */
export type UpdatePostRequest = {
  body?: string | null;
  tags?: Array<string> | null;
  title?: string | null;
};

export type UserResponse = {
  display_name: string;
  email: string;
  id: string;
  role: UserRole;
};

export type UserRole = "admin" | "member" | "guest";

export type ListPostsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Filter by status discriminant, e.g. `published`.
     */
    status?: string;
    sort?: PostSort;
    limit?: number;
    cursor?: string;
  };
  url: "/posts";
};

export type ListPostsResponses = {
  200: ListResponsePostResponse;
};

export type ListPostsResponse = ListPostsResponses[keyof ListPostsResponses];

export type CreatePostData = {
  body: CreatePostRequest;
  path?: never;
  query?: never;
  url: "/posts";
};

export type CreatePostErrors = {
  400: ErrorResponse;
};

export type CreatePostError = CreatePostErrors[keyof CreatePostErrors];

export type CreatePostResponses = {
  200: PostResponse;
};

export type CreatePostResponse = CreatePostResponses[keyof CreatePostResponses];

export type DeletePostData = {
  body?: never;
  path: {
    /**
     * Post id
     */
    id: string;
  };
  query?: never;
  url: "/posts/{id}";
};

export type DeletePostErrors = {
  404: ErrorResponse;
};

export type DeletePostError = DeletePostErrors[keyof DeletePostErrors];

export type DeletePostResponses = {
  /**
   * Deleted
   */
  204: void;
};

export type DeletePostResponse = DeletePostResponses[keyof DeletePostResponses];

export type GetPostData = {
  body?: never;
  path: {
    /**
     * Post id
     */
    id: string;
  };
  query?: never;
  url: "/posts/{id}";
};

export type GetPostErrors = {
  404: ErrorResponse;
};

export type GetPostError = GetPostErrors[keyof GetPostErrors];

export type GetPostResponses = {
  200: PostResponse;
};

export type GetPostResponse = GetPostResponses[keyof GetPostResponses];

export type UpdatePostData = {
  body: UpdatePostRequest;
  path: {
    /**
     * Post id
     */
    id: string;
  };
  query?: never;
  url: "/posts/{id}";
};

export type UpdatePostErrors = {
  404: ErrorResponse;
};

export type UpdatePostError = UpdatePostErrors[keyof UpdatePostErrors];

export type UpdatePostResponses = {
  200: PostResponse;
};

export type UpdatePostResponse = UpdatePostResponses[keyof UpdatePostResponses];

export type ListCommentsData = {
  body?: never;
  path: {
    /**
     * Post id
     */
    id: string;
  };
  query?: never;
  url: "/posts/{id}/comments";
};

export type ListCommentsResponses = {
  200: ListResponseComment;
};

export type ListCommentsResponse =
  ListCommentsResponses[keyof ListCommentsResponses];

export type CreateCommentData = {
  body: CreateCommentRequest;
  path: {
    /**
     * Post id
     */
    id: string;
  };
  query?: never;
  url: "/posts/{id}/comments";
};

export type CreateCommentResponses = {
  200: Comment;
};

export type CreateCommentResponse =
  CreateCommentResponses[keyof CreateCommentResponses];

export type ListUsersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users";
};

export type ListUsersResponses = {
  200: ListResponseUserResponse;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type CreateUserData = {
  body: CreateUserRequest;
  path?: never;
  query?: never;
  url: "/users";
};

export type CreateUserResponses = {
  200: UserResponse;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type GetUserData = {
  body?: never;
  path: {
    /**
     * User id
     */
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type GetUserErrors = {
  404: ErrorResponse;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
  200: UserResponse;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];
