// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://openapi.json` | (string & {});
};

export type CreatePostRequest = {
  body: string;
  /**
   * Optional tags — shows Option<Vec<T>> handling in both outputs.
   */
  tags?: Array<string> | null;
  title: string;
};

export type ErrorResponse = {
  code: string;
  message: string;
};

/**
 * Generic list wrapper — ts-rs keeps the generic, OpenAPI monomorphizes it.
 */
export type ListResponsePostResponse = {
  bookmark?: string | null;
  items: Array<{
    body: string;
    created_at: number;
    id: string;
    status: PostStatus;
    title: string;
  }>;
};

export type PostResponse = {
  body: string;
  created_at: number;
  id: string;
  status: PostStatus;
  title: string;
};

/**
 * Tagged enum — the interesting case: compare how serde `tag`/`rename_all`
 * is rendered by ts-rs vs the OpenAPI route.
 */
export type PostStatus =
  | {
      type: "draft";
    }
  | {
      published_at: number;
      type: "published";
    };

export type ListPostsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/posts";
};

export type ListPostsResponses = {
  200: ListResponsePostResponse;
};

export type ListPostsResponse = ListPostsResponses[keyof ListPostsResponses];

export type CreatePostData = {
  body: CreatePostRequest;
  path?: never;
  query?: never;
  url: "/posts";
};

export type CreatePostErrors = {
  400: ErrorResponse;
};

export type CreatePostError = CreatePostErrors[keyof CreatePostErrors];

export type CreatePostResponses = {
  200: PostResponse;
};

export type CreatePostResponse = CreatePostResponses[keyof CreatePostResponses];

export type GetPostData = {
  body?: never;
  path: {
    /**
     * Post id
     */
    id: string;
  };
  query?: never;
  url: "/posts/{id}";
};

export type GetPostErrors = {
  404: ErrorResponse;
};

export type GetPostError = GetPostErrors[keyof GetPostErrors];

export type GetPostResponses = {
  200: PostResponse;
};

export type GetPostResponse = GetPostResponses[keyof GetPostResponses];
