// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatePostRequest = { title: string, body: string, 
/**
 * Optional tags — shows Option<Vec<T>> handling in both outputs.
 */
tags: Array<string> | null, };
