// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Generic list wrapper — ts-rs keeps the generic, OpenAPI monomorphizes it.
 */
export type ListResponse<T> = { items: Array<T>, bookmark: string | null, };
