// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tagged enum — the interesting case: compare how serde `tag`/`rename_all`
 * is rendered by ts-rs vs the OpenAPI route.
 */
export type PostStatus = { "type": "draft" } | { "type": "published", published_at: bigint, };
