// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostStatus } from "./PostStatus";

export type PostResponse = { id: string, title: string, body: string, status: PostStatus, created_at: bigint, };
