/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_posts"];
        put?: never;
        post: operations["create_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_post"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreatePostRequest: {
            body: string;
            /** @description Optional tags — shows Option<Vec<T>> handling in both outputs. */
            tags?: string[] | null;
            title: string;
        };
        ErrorResponse: {
            code: string;
            message: string;
        };
        /** @description Generic list wrapper — ts-rs keeps the generic, OpenAPI monomorphizes it. */
        ListResponse_PostResponse: {
            bookmark?: string | null;
            items: {
                body: string;
                /** Format: int64 */
                created_at: number;
                id: string;
                status: components["schemas"]["PostStatus"];
                title: string;
            }[];
        };
        PostResponse: {
            body: string;
            /** Format: int64 */
            created_at: number;
            id: string;
            status: components["schemas"]["PostStatus"];
            title: string;
        };
        /**
         * @description Tagged enum — the interesting case: compare how serde `tag`/`rename_all`
         *     is rendered by ts-rs vs the OpenAPI route.
         */
        PostStatus: {
            /** @enum {string} */
            type: "draft";
        } | {
            /** Format: int64 */
            published_at: number;
            /** @enum {string} */
            type: "published";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_posts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse_PostResponse"];
                };
            };
        };
    };
    create_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePostRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Post id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
